### ISSUE TITLE
Non-ideal Wires cause Singular Matrix error

### ISSUE THREAD

**Issue by binhong87** [hausen/circuit-simulator#4] opened 2016-08-11 03:05 UTC
I think Non-ideal Wires in your version are causing some strange Singular Matrix errors.
It does not happen in Falstad's original version.
Two wires NOT in circuit, but connected to each other, will cause error.
Like this one.
$ 1 5.0E-6 382.76258214399064 43 5.0 43
v 80 240 176 240 0 0 40.0 10.0 0.0 0.0 0.5
s 64 128 144 128 0 0 false
s 176 112 256 112 0 0 false
s 176 240 272 240 0 0 false
r 496 272 576 272 0 100.0
r 496 192 576 192 0 100.0
w 80 240 112 352 0
w 336 192 416 272 0
w 272 240 336 192 0
w 416 192 496 192 0
w 416 272 496 272 0
w 336 192 416 192 0
w 496 192 496 144 0
w 384 64 464 64 0
w 576 144 576 192 0
w 576 192 576 272 0
w 576 272 576 336 0
w 112 352 576 336 0
w 496 272 496 224 0
w 464 64 576 64 0
w 608 224 608 272 0
w 608 272 576 272 0

And this one too.
$ 1 5.0E-6 382.76258214399064 43 5.0 43
v 48 144 144 144 0 0 40.0 10.0 0.0 0.0 0.5
s 176 96 240 96 0 1 false
s 272 128 352 128 0 1 false
s 272 48 352 48 0 1 false
w 528 192 624 192 0
w 240 96 272 128 0
w 480 96 464 160 0
w 176 96 144 144 0
w 448 272 80 256 0
r 384 160 464 160 0 100.0
r 400 96 480 96 0 100.0
w 48 144 80 256 0
w 448 272 464 160 0
w 80 416 224 480 0
w 272 48 240 96 0

Please help if you could, I am trying to use this simulator in an educational product.
Thanks.
Bin

**Comment by hausen** [comment] 2016-08-11 03:51
Fixed. Duplicate of #3.

Regarding your use of this simulator in a product, you may have to contact the original author, Paul Falstad at http://www.falstad.com/licensing.html .

**Closed** 2016-08-11 03:51 UTC
Labels: duplicate

**Comment by binhong87** [comment] 2016-08-11 03:58
Thanks for your response.
